[wokwi]
version = 1
elf = ".pio/build/esp32s3_fancy_display/PIO-0.0.0-esp32s3_fancy_display-0000000-main.elf"
firmware = ".pio/build/esp32s3_fancy_display/PIO-0.0.0-esp32s3_fancy_display-0000000-main.bin"
[[net.forward]]
from = "localhost:8180"
to = "target:80"
